#In this notebook, we are going to cover some of the most fundamental concept of tensors using tensorflow


In [ ]:
## introduction to tensors

In [1]:
import tensorflow as tf 
print(tf.__version__)

2.12.0


In [5]:
#creating tensors with tf.constant()
scalar =  tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
#check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [8]:

#create a vector
vector = tf.constant([10, 10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [9]:
#check the dimensions of our vector
vector.ndim

1

In [10]:
#create a matrix (has more than one dimension)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [11]:
matrix.ndim

2

In [13]:
#create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype=tf.float16)#specify the data type with dtype parameter 
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
#what's the number dimension of another matrix
another_matrix.ndim

2